excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://resbaztraining.github.io
title: Training
email: 
author: Isabell Kiral-Kornek
description: training notes
paginate: 5
google_analytics: 