excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://resbaztraining.github.io
title: Training
email: isa.kiral@gmail.com
author: Isabell Kiral-Kornek
description: training notes
paginate: 10
google_analytics: 
