excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://isakiko.github.io/ThreeJS-course
title: Training
email: isa.kiral@gmail.com
author: Isabell Kiral-Kornek
description: training notes
paginate: 10
google_analytics: 
